### ISSUE TITLE
Could not initialize class com.amazonaws.http.conn.ssl.SdkTLSSocketFactory

### ISSUE THREAD

**Issue by tkiansoon** [mso-net/lucee-aws#37]
We implement the lucee-aws library and getting ready to deploy to production, somehow it fails to load the SdkTLSSocketFactory class, but it works in our Dev & QA environment. We are using Lucee 4.5.5.006 in all environments. We installed the SSL certification for aws. Any help is great appreciated.

`Could not initialize class com.amazonaws.http.conn.ssl.SdkTLSSocketFactory 
at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.getPreferredSocketFactory(ApacheConnectionManagerFactory.java:87):87 
at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.create(ApacheConnectionManagerFactory.java:65):65 
at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.create(ApacheConnectionManagerFactory.java:58):58 
at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:51):51 
at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:39):39 
at com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:301):301 
at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:164):164 
at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:523):523 
at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:503):503 
at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:485):485 
at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:457):457 
at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:439):439 
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method):-2 
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62):62 
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45):45 
at java.lang.reflect.Constructor.newInstance(Constructor.java:423):423 
at lucee.runtime.reflection.pairs.ConstructorInstance.invoke(ConstructorInstance.java:52):52 
at lucee.runtime.reflection.Reflector.callConstructor(Reflector.java:809):809 
at lucee.runtime.java.JavaObject.init(JavaObject.java:295):295 
at lucee.runtime.java.JavaObject.call(JavaObject.java:222):222 
at lucee.runtime.java.JavaObject.call(JavaObject.java:259):259 
at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:743):743 
at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1596):1596 
at cfc.aws.s3_cfc$cf.udfCall1(/cfc/aws/s3.cfc:22):22 
at cfc.aws.s3_cfc$cf.udfCall(/cfc/aws/s3.cfc):-1 
`

**Comment by SimonHooker** [comment]
Hi there, I'm afraid I don't have a Lucee environment that old to hand to look into this.  Are you certain that dev, QA, and production all run the same environments?  If the issue is only present in production that indicates that the environments are not comparable.

Additionally 4.5.5.006 is quite old now, to the point where I would query whether it would be a good idea to update to 5.x which is the active version of Lucee.

The error is coming ultimately from within the AWS SDK which would indicate something along the lines of an incompatible version of Java potentially, or that you have a Java library on production which is not present on QA/Dev which is conflicting with parts of the AWS SDK included within this repository
